spring:
  main:
    banner-mode: off

db:
  source:
    url: jdbc:postgresql://localhost:5432/source_db
    username: postgres
    password: 123456

  postgres:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: 123456

  mysql:
    url: jdbc:mysql://localhost:3306/mysql_db
    username: root
    password: 123456
